### ISSUE TITLE
Hubot Collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/hubot-test#1]

**Comment by stoe** [comment]
:wave:

**Comment by githubteacher** [comment]
:tada: @stoe is now a repository collaborator. :balloon:

**Comment by stoe** [comment]
:wave:

**Comment by githubteacher** [comment]
:tada: @stoe is now a repository collaborator. :balloon:

**Comment by stoe** [comment]
:wave: @nathos

**Comment by nathos** [comment]
👋

**Comment by githubteacher** [comment]
:tada: @stoe and @nathos are now  repository collaborators. :balloon:

**Comment by githubteacher** [comment]
:tada: @nathos is now a repository collaborator. :balloon:
